[package]
name = "PPOPT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ppopt"
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version = "0.21.1", features = ["extension-module", "abi3-py37"]}

