# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PPOPT CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: PPOPT_ENV
          python-version: ${{ matrix.python-version }}

      - name: Test conda installation
        shell: bash -l {0}
        run: conda info

      - name: Install Packages
        shell: bash -l {0}
        run: pip install flake8 numpy matplotlib scipy numba gurobipy pytest setuptools psutil pathos plotly daqp

      - name: Install glpk
        shell: bash -l {0}
        run: conda install -c conda-forge cvxopt
  
      - name: Install Quadprog
        shell: bash -l {0}
        run: pip install git+https://github.com/HKaras/quadprog/
        
      - name: Run tests
        shell: bash -l {0}
        run: pytest --disable-pytest-warnings
